### ISSUE TITLE
Trezor issues in HEAD

### ISSUE THREAD

**Issue by Joukehofman** [spesmilo/electrum#1668]
Restore a wallet or import keys, Hardware wallet -> use a drive you have already set up, TREZOR Wallet -> crash:
```

Traceback (most recent call last):
  File "./electrum", line 319, in <module>
    d.init_gui(config, plugins)
  File "/home/user/Electrum/electrum/lib/daemon.py", line 228, in init_gui
    self.gui.main()
  File "/home/user/Electrum/electrum/gui/qt/__init__.py", line 184, in main
    self.config.get('url')):
  File "/home/user/Electrum/electrum/gui/qt/__init__.py", line 156, in start_new_window
    wallet = self.daemon.load_wallet(path, self.get_wizard)
  File "/home/user/Electrum/electrum/lib/daemon.py", line 178, in load_wallet
    wallet = wizard.run(self.network, storage)
  File "/home/user/Electrum/electrum/gui/qt/installwizard.py", line 165, in run
    wallet = WizardBase.run(self, *args)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 147, in run
    cr, wallet = self.create_or_restore(storage)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 228, in create_or_restore
    wallet = self.create_wallet(storage, wallet_type, kind)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 241, in create_wallet
    wallet.plugin.on_create_wallet(wallet, self)
  File "/home/user/Electrum/electrum/plugins/trezor/qt_generic.py", line 295, in on_create_wallet
    on_error=lambda info: exc_info.extend(info))
  File "/home/user/Electrum/electrum/plugins/trezor/plugin.py", line 222, in setup_device
    device_info = devmgr.select_device(wallet, self)
  File "/home/user/Electrum/electrum/lib/plugins.py", line 435, in select_device
    infos = self.unpaired_device_infos(wallet.handler, plugin, devices)
  File "/home/user/Electrum/electrum/lib/plugins.py", line 414, in unpaired_device_infos
    devices = self.scan_devices(handler)
  File "/home/user/Electrum/electrum/lib/plugins.py", line 458, in scan_devices
    devices.append(Device(d['path'], d['interface_number'],
KeyError: 'interface_number'
```

And with Trezor disconnected: 
```

Traceback (most recent call last):
  File "./electrum", line 319, in <module>
    d.init_gui(config, plugins)
  File "/home/user/Electrum/electrum/lib/daemon.py", line 228, in init_gui
    self.gui.main()
  File "/home/user/Electrum/electrum/gui/qt/__init__.py", line 184, in main
    self.config.get('url')):
  File "/home/user/Electrum/electrum/gui/qt/__init__.py", line 156, in start_new_window
    wallet = self.daemon.load_wallet(path, self.get_wizard)
  File "/home/user/Electrum/electrum/lib/daemon.py", line 178, in load_wallet
    wallet = wizard.run(self.network, storage)
  File "/home/user/Electrum/electrum/gui/qt/installwizard.py", line 165, in run
    wallet = WizardBase.run(self, *args)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 147, in run
    cr, wallet = self.create_or_restore(storage)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 228, in create_or_restore
    wallet = self.create_wallet(storage, wallet_type, kind)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 241, in create_wallet
    wallet.plugin.on_create_wallet(wallet, self)
  File "/home/user/Electrum/electrum/plugins/trezor/qt_generic.py", line 295, in on_create_wallet
    on_error=lambda info: exc_info.extend(info))
  File "/home/user/Electrum/electrum/plugins/trezor/plugin.py", line 223, in setup_device
    devmgr.pair_wallet(wallet, device_info.device.id_)
AttributeError: 'NoneType' object has no attribute 'device'
```

**Comment by ecdsa** [comment]
@kyuupichan can you have a look please?

**Comment by kyuupichan** [comment]
What version of trezor libraries are you using?  Can you try updating?

**Comment by Joukehofman** [comment]
What do you mean by libraries? I've updated the trezors firmware yesterday and I pulled master from git yesterday.

**Comment by ecdsa** [comment]
@Joukehofman the python-trezor library

**Comment by ecdsa** [comment]
maybe we should detect the trezorlib version

**Comment by Joukehofman** [comment]
Ok, right. I updated to 0.6.11 and still got this error with trezor plugged in.
`Traceback (most recent call last):
  File "/home/user/Electrum/electrum/gui/qt/main_window.py", line 395, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/Electrum/electrum/gui/qt/__init__.py", line 156, in start_new_window
    wallet = self.daemon.load_wallet(path, self.get_wizard)
  File "/home/user/Electrum/electrum/lib/daemon.py", line 178, in load_wallet
    wallet = wizard.run(self.network, storage)
  File "/home/user/Electrum/electrum/gui/qt/installwizard.py", line 165, in run
    wallet = WizardBase.run(self, *args)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 147, in run
    cr, wallet = self.create_or_restore(storage)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 228, in create_or_restore
    wallet = self.create_wallet(storage, wallet_type, kind)
  File "/home/user/Electrum/electrum/lib/wizard.py", line 241, in create_wallet
    wallet.plugin.on_create_wallet(wallet, self)
  File "/home/user/Electrum/electrum/plugins/trezor/qt_generic.py", line 295, in on_create_wallet
    on_error=lambda info: exc_info.extend(info))
  File "/home/user/Electrum/electrum/plugins/trezor/plugin.py", line 223, in setup_device
    devmgr.pair_wallet(wallet, device_info.device.id_)
AttributeError: 'NoneType' object has no attribute 'device'
`

**Comment by kyuupichan** [comment]
Your device wasn't plugged in.  It now gives an error message.

**Comment by kyuupichan** [comment]
Please confirm if what doesn't work with git HEAD does work with 2.5.4, and that you're certain no other apps (bridge, Chrome browser) are using your device.

**Comment by kyuupichan** [comment]
Seems to have been a package conflict on OP's machine; removing old package fixed it
