### ISSUE TITLE
Watchtower does not start

### ISSUE THREAD

**Issue by emanuelelaface** [spesmilo/electrum#5896]
I am testing the LN watchtower. I followed the instructions in [https://electrum.org/talks/lightning/tlc.html#slide22](https://electrum.org/talks/lightning/tlc.html#slide22) but once electrum runs as daemon I do not see the port 12345 open (the one in the example that I used in the configuration).

I can see the config file in the wallet directory with the correct watchtower_host and watchtower_port.
I tried also to run the same configuration with the GUI instead of the CLI but I do not see any difference.

**Comment by emanuelelaface** [comment]
Ok, looking at the code the is an if run_watchtower in the config that has to be set in order to start the watchtower daemon. So in the example of the slide it is missing a line like 
`$carol setconfig setconfig -o run_watchtower true`
If I add this, I can see the port listening. The client is not trying to connect to it, but this seems another problem now.

**Comment by emanuelelaface** [comment]
With the latest commit I can see Electrum sending a jsonrpc request to the watchtower, but the watchtower rise an error:
```
I | daemon.WatchTowerServer | {"jsonrpc": "2.0", "method": "get_ctn", "params": ["46<HIDE>", "bc1<HIDE>"], "id": 1}
E | root | 'NoneType' object has no attribute 'sweepstore'
Traceback (most recent call last):
  File "/home/ema/.local/lib/python3.7/site-packages/jsonrpcserver/dispatcher.py", line 123, in handle_exceptions
    yield handler
  File "/home/ema/.local/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py", line 40, in safe_call
    lookup(methods, request.method), *request.args, **request.kwargs
  File "/home/ema/.local/lib/python3.7/site-packages/jsonrpcserver/async_dispatcher.py", line 34, in call
    return await validate_args(method, *args, **kwargs)(*args, **kwargs)
  File "/Bitcoin/electrum_watchtower/electrum/daemon.py", line 171, in get_ctn
    return await self.lnwatcher.sweepstore.get_ctn(*args)
AttributeError: 'NoneType' object has no attribute 'sweepstore'
```

**Comment by ecdsa** [comment]
indeed, there is a bug
it seems to have been introduced in 90ce9f195b97978becdabd62e618dda9b8daba42

**Comment by ecdsa** [comment]
note: the watchtower is now tested in regtests: 4ec86d36a826099f823a95d18c13b2a7aa84c6ea
