### ISSUE TITLE
Regression in 9d40fb2 - AttributeError: 'module' object has no attribute 'frozen'

### ISSUE THREAD

**Issue by atweiden** [spesmilo/electrum#991]
The culprit appears to be https://github.com/spesmilo/electrum/commit/9d40fb2ea8b347e08b4b64897537e2197d4325e3. Electrum QT interface crashes on startup.

```
Traceback (most recent call last):
  File "/bin/electrum", line 244, in <module>
    gui.main(url)
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 191, in main
    self.init_lite()
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/__init__.py", line 134, in init_lite
    actuator = lite_window.MiniActuator(self.main_window)
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/lite_window.py", line 610, in __init__
    self.themes = load_theme_paths()
  File "/usr/lib/python2.7/site-packages/electrum_gui/qt/lite_window.py", line 79, in load_theme_paths
    theme_paths.update(theme_dirs_from_prefix(util.data_dir()))
  File "/usr/lib/python2.7/site-packages/electrum/util.py", line 69, in data_dir
    if getattr(sys, 'frozen'):
AttributeError: 'module' object has no attribute 'frozen'
```

**Comment by BrendaFdez** [comment]
I came here to report this same issue. If there's a temporary solution I'd be glad to know. Also in case you need to debug, if you can't reproduce it, I could help you. It happens when trying to generate multisig wallet, or, after introducing the seed for standard wallets, when it starts generating the keys. I'm on the latest testing version. The output in the terminal I'm getting is exactly the same as @atweiden
