### ISSUE TITLE
trezor one device not detecting on electrum-3.0.6/3.1.0 python tool

### ISSUE THREAD

**Issue by sharath1990** [spesmilo/electrum#4082]
I am using latest python-trezor v0.9.1 and electrum-3.0.6/3.1.0 wallet but that electrum wallet not able to detect trezor one device. it says AttributeError: module 'trezorlib.client' has no attribute 'types' and AttributeError: module 'trezorlib.transport_hid' has no attribute 'DEVICE_IDS'
only python electrum tool is not able to detect the device but electrum windows tool is able to detect it.
Please check with issue and resolve it as soon as possible.

**Comment by SomberNight** [comment]
python-trezor 0.9.0+ will only work with electrum 3.1.0+

Make sure python-trezor is installed for python3, and perhaps try uninstalling it "multiple times" until pip says it is not installed, and then install it again, to make sure only the version you want is installed.

If you are getting either of those errors with python-trezor 0.9.1 with electrum 3.1.0, then please provide a trace.

**Comment by SomberNight** [comment]
What do you mean by "python electrum tool"?

**Comment by sharath1990** [comment]
its means the source code language used for electrum bitcoin wallet is python.

https://electrum.org/#download
In the above link you have "Installation from Python sources": in that you have windows tab and i am using Install Electrum-3.1.0.zip

**Comment by SomberNight** [comment]
Using the same python interpreter you are experiencing the issue with, what does the following print:
```
python3 -m pip show trezor
```

**Comment by sharath1990** [comment]
Please do check the screenshot for  python3 -m pip show trezor.


________________________________

**Comment by sharath1990** [comment]
![screenshot](https://user-images.githubusercontent.com/36299411/37266892-2fe0a8cc-25e3-11e8-951b-d27c1fb8f527.png)

**Comment by SomberNight** [comment]
Could you describe a minimal example of how to reproduce the errors?

**Comment by sharath1990** [comment]
Yep,
Just go to Electrum-3.0.6 folder path in command line and type "python electrum" click enter and gui will be opened in that click next and select "standard wallet" and click next and select "Use a hardware device" and click next that's it. error will be produced.

**Comment by SomberNight** [comment]
> Just go to Electrum-3.0.6 folder path

Again, as I said:

> python-trezor 0.9.0+ will only work with electrum 3.1.0+

**Comment by sharath1990** [comment]
even if i used Electrum-3.1.0 same issue i am getting.

**Comment by SomberNight** [comment]
See https://github.com/spesmilo/electrum/issues/3928

Please provide a stack trace for the error you are getting because I cannot reproduce.

**Comment by sharath1990** [comment]
if i use Electrum-3.1.0  i am not getting AttributeError, but device is not detecting, plz find the screen shots that i tried are electrum-3.0.6 with python-trezor v0.9.0; electrum-3.1.0 and python-trezor v0.9.1; and other combination.
![p1](https://user-images.githubusercontent.com/36299411/37455475-2d08aac8-2863-11e8-8652-7c21fb3bdf33.png)
![p2](https://user-images.githubusercontent.com/36299411/37455476-2d389ca6-2863-11e8-826d-389b7146f04f.png)
![p3](https://user-images.githubusercontent.com/36299411/37455479-2d65569c-2863-11e8-8b5b-8476c4e45805.png)
![p4](https://user-images.githubusercontent.com/36299411/37455480-2d8fc9ae-2863-11e8-9d2f-6b8937959f40.png)
![p5](https://user-images.githubusercontent.com/36299411/37455482-2de52444-2863-11e8-84bc-3a1c787e50e1.png)

**Comment by SomberNight** [comment]
Forget about electrum 3.0.6; that error is expected; only test with electrum 3.1+.
Do you have proxy settings enabled in Electrum? Please try with 3.1.1.

**Comment by sharath1990** [comment]
what do you mean by proxy setting?

**Comment by SomberNight** [comment]
I mean a networking proxy set up inside Electrum:

![proxy](https://user-images.githubusercontent.com/29142493/37460173-be6c1fe0-284a-11e8-84cf-599086ea2046.PNG)

There is a bug related to that and hw wallets in 3.1.0;
but regardless, please try with 3.1.1

**Comment by sharath1990** [comment]
![p6](https://user-images.githubusercontent.com/36299411/37460261-b4f94bba-2870-11e8-90ac-3f04078cafcb.png)

**Comment by SomberNight** [comment]
please try with the `-v` flag, and provide logs
`python electrum -v`

**Comment by sharath1990** [comment]
yeah done.
![p7](https://user-images.githubusercontent.com/36299411/37461095-50cfea9c-2873-11e8-92f5-5336fad73660.png)

**Comment by SomberNight** [comment]
Just to be clear, it works with the official binary, but not when running from source?

**Comment by SomberNight** [comment]
I believe you are missing the libusb dll; that raises an exception, and all transports for trezor fail.
https://github.com/spesmilo/electrum/commit/78a9424c48bd47d0d89470c6960bbe75f49bae64
If you want to use the webusb transport, you will need to make sure python can import the libusb dll.
You can e.g. manually download it and paste it in the root python folder.

In any case, we should minimise the problem and not let all the transports fail.

**Comment by SomberNight** [comment]
Please try on current master. :)

**Comment by sharath1990** [comment]
I took the current master branch & installed respective packages but it still not works?
![p8](https://user-images.githubusercontent.com/36299411/37463141-4f9572f8-287a-11e8-888d-234ad07d984d.png)

**Comment by SomberNight** [comment]
Did you run `python setup.py install`? As in https://github.com/spesmilo/electrum#development-version

**Comment by sharath1990** [comment]
yeah, after installing still getting an issue.
![p9](https://user-images.githubusercontent.com/36299411/37464945-dc6c35c2-287f-11e8-9aaf-056ed8c43e2d.png)

**Comment by SomberNight** [comment]
Please follow the guide I linked above; that too is covered there.

**Comment by sharath1990** [comment]
after this step 'python setup.py install' still it not works for me.
![p10](https://user-images.githubusercontent.com/36299411/37465697-dc16ebc4-2881-11e8-9e12-6f146ba642c7.png)

**Comment by SomberNight** [comment]
please run with `-v` because without logs it is a black box, literally.

**Comment by sharath1990** [comment]
okay.
![p11](https://user-images.githubusercontent.com/36299411/37465846-4d6e5afa-2882-11e8-98ea-e3feb6cc3b23.png)

**Comment by SomberNight** [comment]
Can you confirm that it works with the official binary?

**Comment by sharath1990** [comment]
what do you mean by official binary?

**Comment by SomberNight** [comment]
I mean the exe files at https://electrum.org/#download

**Comment by SomberNight** [comment]
Ok, I can reproduce. It's still libusb somehow.

**Comment by SomberNight** [comment]
Ok, for the moment, I suggest downloading the libusb dll, and copying to your python path (e.g. `%localappdata%\Programs\Python\Python36-32`); as we do for the binaries in https://github.com/spesmilo/electrum/commit/78a9424c48bd47d0d89470c6960bbe75f49bae64.

The problem is that python-trezor 0.9.0 and 0.9.1 (but not the current master) import all the transports :/
```
Traceback (most recent call last):
  File "...\electrum\lib\base_wizard.py", line 208, in choose_hw_device
    u = devmgr.unpaired_device_infos(None, plugin)
  File "...\electrum\lib\plugins.py", line 471, in unpaired_device_infos
    client = self.create_client(device, handler, plugin)
  File "...\electrum\lib\plugins.py", line 347, in create_client
    client = plugin.create_client(device, handler)
  File "...\electrum\plugins\trezor\trezor.py", line 171, in create_client
    from trezorlib.device import TrezorDevice
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\trezorlib\device.py", line 23, in <module>
    from .transport_webusb import WebUsbTransport
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\trezorlib\transport_webusb.py", line 24, in <module>
    import usb1
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\libusb1-1.6.4-py3.6.egg\usb1\__init__.py", line 61, in <module>
    from . import libusb1
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\libusb1-1.6.4-py3.6.egg\usb1\libusb1.py", line 199, in <module>
    libusb = _loadLibrary()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-packages\libusb1-1.6.4-py3.6.egg\usb1\libusb1.py", line 173, in _loadLibrary
    return dll_loader('libusb-1.0' + suffix, **loader_kw)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
[DeviceMgr] error trezor
```

**Comment by SomberNight** [comment]
See https://github.com/trezor/python-trezor/issues/218#issuecomment-367026789

**Comment by SomberNight** [comment]
Ok, it should now work on current master.
