### ISSUE TITLE
Importing single private keys is broken

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrum#2873]
Steps to reproduce:
- Create a new wallet with the wizard
    - choose `standard wallet`
    - choose `use public or private keys`
    - type in a single private key (not something hierarchic, just a single privkey)
    - keep password empty, and click next
    - the wizard will hang saying `Please wait...`, and the following trace happens:

```
Traceback (most recent call last):
  File "/home/user/wspace/electrum/gui/qt/main_window.py", line 436, in new_wallet
    self.gui_object.start_new_window(full_path, None)
  File "/home/user/wspace/electrum/gui/qt/__init__.py", line 178, in start_new_window
    wallet = wizard.run_and_get_wallet()
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 274, in run_and_get_wallet
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 88, in new
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.on_wallet_type)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 106, in on_wallet_type
    self.run(action)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 138, in choose_keystore
    self.choice_dialog(title=title, message=message, choices=choices, run_next=self.run)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 161, in restore_from_key
    self.add_xpub_dialog(title=title, message=message, run_next=self.on_restore_from_key, is_valid=v)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 168, in on_restore_from_key
    self.on_keystore(k)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 307, in on_keystore
    self.run('create_wallet')
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 61, in run
    f(*args)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 333, in create_wallet
    self.request_password(run_next=self.on_password)
  File "/home/user/wspace/electrum/gui/qt/installwizard.py", line 96, in func_wrapper
    run_next(*out)
  File "/home/user/wspace/electrum/lib/base_wizard.py", line 346, in on_password
    self.wallet = Standard_Wallet(self.storage)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1586, in __init__
    Deterministic_Wallet.__init__(self, storage)
  File "/home/user/wspace/electrum/lib/wallet.py", line 1425, in __init__
    Abstract_Wallet.__init__(self, storage)
  File "/home/user/wspace/electrum/lib/wallet.py", line 102, in __init__
    self.load_keystore()
  File "/home/user/wspace/electrum/lib/wallet.py", line 1547, in load_keystore
    xtype = deserialize_xpub(self.keystore.xpub)[0]
AttributeError: 'Imported_KeyStore' object has no attribute 'xpub'
```

Probably introduced in 63a1db117282eb5526f5ef55b4bc720ae820fdde.

**Comment by ecdsa** [comment]
when a private key is imported, we need to know the type of script where they will be used.
the private key format already has an extra byte that signals if compressed public keys should be used.
I think it makes sense to extend that format too, as we did for xpub/xprv

**Comment by ecdsa** [comment]
ok, I made a proposal to the mailing list: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-September/015007.html
This discussion might take a while. 
In the meantime, we should probably disable exporting/importing private keys in segwit wallets.
