### ISSUE TITLE
AttributeError: 'MySortModel' object has no attribute 'item'

### ISSUE THREAD

**Issue by ecdsa** [spesmilo/electrum#6168]
> Traceback (most recent call last):
>   File "/opt/electrum/electrum/gui/qt/main_window.py", line 429, in on_network_qt
>     self.on_invoice_status(*args)
>   File "/opt/electrum/electrum/gui/qt/main_window.py", line 1492, in on_invoice_status
>     self.invoice_list.update_item(key, req)
>   File "/opt/electrum/electrum/gui/qt/invoice_list.py", line 83, in update_item
>     item = model.item(row, 0)
> AttributeError: 'MySortModel' object has no attribute 'item'
> 

probably introduced in 93c90a30f03ce2ab1254e83ce5e143dbfd6e1b0f
