### ISSUE TITLE
Load Tx From QR code now crashes program. 

### ISSUE THREAD

**Issue by neocogent** [spesmilo/electrum#3207]
Testing out using QR codes for signing txs. Snapped a shot of unsigned tx QR code and then trying to load back in to sign. Was working on 3.0 release but after pulling master today it now crashes with this dump:

```
Traceback (most recent call last):
  File "/home/chris/Dev/electrum/gui/qt/main_window.py", line 2055, in read_tx_from_qrcode
    data = data.decode('utf8')
AttributeError: 'str' object has no attribute 'decode'
Aborted

```
Appears to be Python3 conversion issue.

I tried to track this down myself but got confused about what data should be and rather than wasting my time decided to pass it on to someone who's familiar with it. In Python3 it appears the data returned by qrscanner is already decoded from utf-8 by str(). So I tried dropping the decode call. But then the data caused a failure in the bitcoin.base_decode (base 43). But comment says data is binary so not sure why decode as base 43 and when I checked it the data has chars outside the base43 char set. So not surprised the decode fails - it ends with a massive negative long and cannot be appended to bytearray. So not sure what should happen here but it's wrong now in Python3 and QR tx cannot be scanned.

**Comment by ecdsa** [comment]
you dont seem to be running the code on master

**Comment by neocogent** [comment]
Indeed. Double checked and for some reason was stuck at a commit from Sep 30 even though I had pulled from upstream master. I did another pull and got up to Nov. 3. So will try again now.

**Comment by neocogent** [comment]
Ok. Treied with latest commit 1ef6926ca77ea252193d6c556df2a70f33546f04 (Nov 3).

Got crash and this dump:

```
Traceback (most recent call last):
  File "/home/chris/Dev/electrum/gui/qt/main_window.py", line 2107, in read_tx_from_qrcode
    self.show_transaction(tx)
  File "/home/chris/Dev/electrum/gui/qt/main_window.py", line 752, in show_transaction
    show_transaction(tx, self, tx_desc)
  File "/home/chris/Dev/electrum/gui/qt/transaction_dialog.py", line 45, in show_transaction
    d = TxDialog(tx, parent, desc, prompt_if_unsaved)
  File "/home/chris/Dev/electrum/gui/qt/transaction_dialog.py", line 128, in __init__
    self.update()
  File "/home/chris/Dev/electrum/gui/qt/transaction_dialog.py", line 180, in update
    tx_hash, status, label, can_broadcast, can_rbf, amount, fee, height, conf, timestamp, exp_n = self.wallet.get_tx_info(self.tx)
  File "/home/chris/Dev/electrum/lib/wallet.py", line 435, in get_tx_info
    tx_hash = tx.txid()
  File "/home/chris/Dev/electrum/lib/transaction.py", line 800, in txid
    ser = self.serialize(witness=False)
  File "/home/chris/Dev/electrum/lib/transaction.py", line 782, in serialize
    txins = var_int(len(inputs)) + ''.join(self.serialize_input(txin, self.input_script(txin, estimate_size)) for txin in inputs)
  File "/home/chris/Dev/electrum/lib/transaction.py", line 782, in <genexpr>
    txins = var_int(len(inputs)) + ''.join(self.serialize_input(txin, self.input_script(txin, estimate_size)) for txin in inputs)
  File "/home/chris/Dev/electrum/lib/transaction.py", line 680, in input_script
    pubkey = safe_parse_pubkey(pubkeys[0])
IndexError: list index out of range
Aborted

```

Seems to be related to just fixed tx loading safe_parse_pubkey

**Comment by estevaocm** [comment]
Hello, I am getting a segmentation fault when trying to load a transaction by QR. I have tried this today with  the 3.0.2 release and next from building from master. I have also installed python-zbar before these tests.
