### ISSUE TITLE
AttributeError("'Network' object has no attribute 'path_finder'")

### ISSUE THREAD

**Issue by alexander-koval** [spesmilo/electrum#7242]
Hello! I'm playing with testnet lightning payments and have some troubles. When I pay invoice, I've got an error AttributeError("'Network' object has no attribute 'path_finder'"). On remote node invoice is settled, but in electrum its stuck on Status "In progress"

What I do:
1. Open channel with trampoline "endurance" 
2. Receive some LN payments 
3. Make LN payment 

[electrum_log_20210424T163303Z_197398.log](https://github.com/spesmilo/electrum/files/6370306/electrum_log_20210424T163303Z_197398.log)

**Comment by SomberNight** [comment]
```
20210424T181121.370913Z |    ERROR | lnworker.LNWallet.[test_wallet] | Exception in pay_invoice: AttributeError("'Network' object has no attribute 'path_finder'")
Traceback (most recent call last):
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/util.py", line 1091, in wrapper
    return await func(*args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnworker.py", line 1119, in pay_invoice
    await self.pay_to_node(
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnworker.py", line 1217, in pay_to_node
    self.network.path_finder.update_liquidity_hints(htlc_log.route, htlc_log.amount_msat)
AttributeError: 'Network' object has no attribute 'path_finder'
20210424T181121.402157Z |    ERROR | gui.qt.main_window.[test_wallet] | on_error
Traceback (most recent call last):
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/gui/qt/util.py", line 913, in run
    result = task.task()
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/gui/qt/main_window.py", line 1549, in task
    return fut.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/util.py", line 1091, in wrapper
    return await func(*args, **kwargs)
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnworker.py", line 1119, in pay_invoice
    await self.pay_to_node(
  File "/home/alexander/Workspace/Python/Electrum/electrum/electrum/lnworker.py", line 1217, in pay_to_node
    self.network.path_finder.update_liquidity_hints(htlc_log.route, htlc_log.amount_msat)
AttributeError: 'Network' object has no attribute 'path_finder'
```

This is a regression from https://github.com/spesmilo/electrum/pull/7152.

@bitromortac the issue is that path_finder is only set if gossip is enabled, so all the liquidity hint stuff, and the blacklisting, won't work otherwise.
We should grep for `network.path_finder` and consider what to do if gossip is disabled.

**Comment by bitromortac** [comment]
Thanks, will have a look.
