### ISSUE TITLE
crash when trying to select "spend from" option in address list

### ISSUE THREAD

**Issue by Rogach** [spesmilo/electrum#8155]
Trying to select "Spend from" in context menu in address list results in Electrum crashing with:

```
File ".../electrum/gui/qt/address_list.py", line 291, in <lambda>
    menu.addAction(_("Spend from"), lambda: self.parent.utxo_list.set_spend_list(coins))
AttributeError: 'UTXOList' object has no attribute 'set_spend_list'. Did you mean: 'get_spend_list'?
```

Seems that the issue was introduced in commit 975cdca47482c043d846eb2ea1533c65d7d4b3d1, `set_spend_list` was removed.
