### ISSUE TITLE
Regression. 553bf986 breaks seed dialog on Ubuntu 16.04

### ISSUE THREAD

**Issue by Raulo** [spesmilo/electrum#3697]
3.0.5 version on Ubuntu is not working with  "I have my own seed": The error is AttributeError: 'QTextEdit' object has no attribute 'text'.

Reverting 553bf986 fixes the problem.

**Comment by SomberNight** [comment]
Yes, there is a follow-up commit because of this.
https://github.com/spesmilo/electrum/commit/41660d26e922876dc653096a973b2ee17ac9996b
