### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'get' via lib/dnssec.py line 192

### ISSUE THREAD

**Issue by shsmith** [spesmilo/electrum#2807]
On git HEAD I am getting this traceback:

```
Traceback (most recent call last):
  File "electrum", line 91, in <module>
    imp.load_module('electrum', *imp.find_module('lib'))
  File "electrum\lib\__init__.py", line 3, in <module>
    from .wallet import Synchronizer, Wallet, Imported_Wallet
  File "electrum\lib\wallet.py", line 64, in <module>
    from .contacts import Contacts
  File "electrum\lib\contacts.py", line 37, in <module>
    from . import dnssec
  File "electrum\lib\dnssec.py", line 192, in <module>
    dns.rrset.from_text('.', 1    , 'IN', 'DNSKEY', '257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU='),
  File "Python27\lib\site-packages\dns\rrset.py", line 145, in from_text
    return from_text_list(name, ttl, rdclass, rdtype, text_rdatas)
  File "Python27\lib\site-packages\dns\rrset.py", line 134, in from_text_list
    rd = dns.rdata.from_text(r.rdclass, r.rdtype, t)
  File "Python27\lib\site-packages\dns\rdata.py", line 436, in from_text
    token = tok.get()
AttributeError: 'unicode' object has no attribute 'get'
```
I updated to the latest dnspython-1.15.0-py2.7.egg but it did not help.

**Comment by ecdsa** [comment]
you are using python2 instead of python3
any idea why?

**Comment by shsmith** [comment]
This must be the first version that no longer works on Python 2.7.
I will try to make it work with Python 3.6

**Comment by shsmith** [comment]
Now I am getting a failure on PyQt4:
```
shsmith@hsmiths-ubuntu:~/electrum$ ./electrum
Traceback (most recent call last):
  File "/home/shsmith/electrum/lib/plugins.py", line 83, in load_plugins
    self.load_plugin(name)
  File "/home/shsmith/electrum/lib/plugins.py", line 102, in load_plugin
    p = loader.load_module(full_name)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/shsmith/electrum/plugins/labels/qt.py", line 3, in <module>
    from PyQt4.QtGui import *
ImportError: No module named 'PyQt4'
Error: Could not import PyQt4 on Linux systems, you may try 'sudo apt-get install python-qt4'
shsmith@hsmiths-ubuntu:~/electrum$ 
```
I successfully ran sudo python3 setup.py install, but it appears not all the dependencies were considered.
I manually installed pyqt4-dev-tools and python-qt4, but that did not help.

**Comment by ecdsa** [comment]
try python3-pyqt4

**Comment by ecdsa** [comment]
fixed in dc9a25b83cc131493adcc2402779fcf6cc816ad0

**Comment by shsmith** [comment]
> try python3-pyqt4

That worked.  Thank you.
