### ISSUE TITLE
Tx description vanishes after RBF fee bump

### ISSUE THREAD

**Issue by EagleTM** [spesmilo/electrum#2341]
When you bump the fee with RBF the tx is replaced with a new tx with a different tx id.
This appears to cause the description entered in the GUI to vanish. The description should be copied over to the new tx, when replacing the old tx.

Obviously the original tx may still get confirmed, I'm not sure if the description is hidden in the background and re-appears.

**Comment by ecdsa** [comment]
that sould fix it; please test :)

**Comment by EagleTM** [comment]
Tried testing - gives traceback when bumping fee (reverted to 2.8.2 default and it works again), maybe other changes at HEAD, I'll test

Traceback (most recent call last):
  File "<path>\gui\qt\history_list.py", line 162, in <lambda>
    menu.addAction(_("Increase fee"), lambda: self.parent.bump_fee_dialog(tx))
  File "<path>\gui\qt\main_window.py", line 2863, in bump_fee_dialog
    tx_label = wallet.get_label(tx.txid())
NameError: global name 'wallet' is not defined Traceback (most recent call last):
  File "<path>\gui\qt\history_list.py", line 162, in <lambda>
    menu.addAction(_("Increase fee"), lambda: self.parent.bump_fee_dialog(tx))
  File "<path>\gui\qt\main_window.py", line 2863, in bump_fee_dialog
    tx_label = wallet.get_label(tx.txid()) NameError: global name 'wallet' is not defined

**Comment by ecdsa** [comment]
sorry I should have tested

**Comment by EagleTM** [comment]
Can confirm. Works to the GUI fee bump window but fails on bump:
Traceback (most recent call last):
  File "<path>\gui\qt\history_list.py", line 162, in <lambda>    menu.addAction(_("Increase fee"), lambda: self.parent.bump_fee_dialog(tx))
    File "<path>\gui\qt\main_window.py", line 2897, i
n bump_fee_dialog
    self.show_transaction(new_tx, desc=tx_label)
TypeError: show_transaction() got an unexpected keyword argument 'desc'

**Comment by EagleTM** [comment]
Can confirm: Works now. Label is kept after bump. No exceptions anymore
