### ISSUE TITLE
multisig with hardware wallets

### ISSUE THREAD

**Issue by ulrichard** [spesmilo/electrum#1093]
A while ago I learned, that multisig in electrum only works with the special electrum wallets, and not other addresses. https://github.com/spesmilo/electrum/issues/929
In the meantime, multisig support is available for both trezor and hw1.
Now, how much effort would it be to extend the multisig support to these harware wallets?
I understand that the hardware and software wallets could not be mixed due to different key derivation, but that's fine with me.

**Comment by ecdsa** [comment]
this was enabled here: c224a9ad9d63b3f20f7e0c796352ba2b0f518a4c
it still requires a 'trezor' type wallet, though

**Comment by ecdsa** [comment]
if you want to test, here is how it works:
 1. create a trezor wallet
 2. create a multisig wallet, and add the trezor xpub as a cosigner
 3. load the multisig transaction in your trezor wallet, and sign it

in the future I will make it so that you won't need a trezor type wallet file

**Comment by ecdsa** [comment]
note: it only works if trezor signs first. trying to fix that...

**Comment by ulrichard** [comment]
This is great news!
But I couldn't get it to work so far. 
If I enable "show tx before broadcast", Clicking the "View" button doesn't open the tx dialog on the multisig wallet. 
If I disable the option, It opens the dialog and I can save the tx to a file or to the clipboard. But when I load the tx in the trezor wallet, I shows status "partially signed (1/2)" which is not good according to your comments. When I then click "sign" I get the error : "'module' object has no attribute 'deserialize'"
So I assume I would just have to figure out a way to get the tx unsigned from the multisig wallet?

**Comment by ecdsa** [comment]
Clicking the "View" button doesn't open the tx dialog on the multisig wallet ?
maybe the tx window is hidden in the background?

**Comment by ulrichard** [comment]
With the latest rev d3104a17b7043815f01d54dd947f7a32c563850d  I can save the unsigned tx.
I had tx windows open in the background on my earlier test. But I had the impression that was when loading the tx from file. Not 100% certain though.
The other error was because I had python-trezor 0.6.3. After upgrading to 0.6.5 I was able to successfully test the workflow. 
Now I'm looking forward to multisig with multible hardware wallets :-)

**Comment by ecdsa** [comment]
ok, now you can sign them in any order. (revision 15f592f)
you can actually already do multisig with multiple hardware wallets: just "restore" the wallet using the xpubs of two trezors

**Comment by ulrichard** [comment]
Would it be a huge effort to support partially signing tx with ledger?
If you can give me some directions, I might give it a try.

**Comment by ecdsa** [comment]
you should ask @btchip for that

**Comment by btchip** [comment]
It should be pretty easy, as long as you're initialized with the NO_2FA_P2SH feature (unfortunately the Python wizard doesn't do it, so you'd have to reinitialize manually or through the Ledger Wallet chrome application). 

Then you need to call startUntrustedTransaction with the redeemScript associated to the key you're signing it and finalizeInputFull instead of finalizeInput.

 I thought multisignature with hardware wallets wasn't generic yet, but if it is I can try to give it a look later in the coming days.

**Comment by aussiehash** [comment]
\*cough\* Electrum multisig now works with Trezor and KeepKey \*cough\*

**Comment by ulrichard** [comment]
With the current git head I get this when trying to sign a tx:

Traceback (most recent call last):
  File "/home/richi/sourcecode/electrum/gui/qt/util.py", line 550, in run
    result = task.task()
  File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line 169, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line 365, in sign_transaction
    inputs = self.tx_inputs(tx, True)
  File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line 404, in tx_inputs
    pubkeys = map(f, x_pubkeys)
  File "/home/richi/sourcecode/electrum/plugins/trezor/plugin.py", line 402, in f
    node = ckd_public.deserialize(xpub)
NameError: global name 'ckd_public' is not defined

**Comment by ulrichard** [comment]
With pull req#1649 I could successfully test the procedure with a trezor and a keepkey.
Should we close this issue, and make a separate one for the ledger?

**Comment by btchip** [comment]
yes that'd probably be best since the P2SH code was missing from the
initial Ledger plugin.


On 27 January 2016 at 21:40, Richard <notifications@github.com> wrote:

> With pull req#1649 I could successfully test the procedure with a trezor
> and a keepkey.
> Should we close this issue, and make a separate one for the ledger?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spesmilo/electrum/issues/1093#issuecomment-175843713>.
>



-- 
Nicolas Bacca
CEO <http://www.simulity.com/>
Mobile +33 6 30 79 86 54 - Skype nicolas_bacca.pro
