### ISSUE TITLE
AttributeError: 'Console' object has no attribute 'completions_visible' (only in --offline)

### ISSUE THREAD

**Issue by Giando** [spesmilo/electrum#6731]
# Crash Report
This crash report has been manually reported because it only occurs in `--offline` mode 😄 

## Traceback
```python
Traceback (most recent call last):
  File "/opt/Electrum-4.0.4/electrum/gui/qt/console.py", line 273, in keyPressEvent
    self.hide_completions()
  File "/opt/Electrum-4.0.4/electrum/gui/qt/console.py", line 154, in hide_completions
    if not self.completions_visible:
AttributeError: 'Console' object has no attribute 'completions_visible'
```
 
## Reporter
This issue was reported by 1 user(s):
Electrum Version | Python Version | Operating System | Wallet Type | Locale | Stack
----------------------- | -------------------- | ------------------------ | --------------- | --------- | --------
4.0.4 | 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0] | Linux-4.19.0-12-amd64-x86_64-with-debian-10.6 | standard | it_IT | ?

## Additional information
In the "Console" tab, already typing the 1st character of the command, without even having sent it, this blocking error occurs.
The error occurs only in `--offline` mode, online works smoothly.
Version 3.3.8 also worked regularly in `--offline`.

**Comment by SomberNight** [comment]
This got broken in https://github.com/spesmilo/electrum/pull/6467

**Comment by SomberNight** [comment]
Thanks for taking the time to open a report manually.

**Comment by Giando** [comment]
You're welcome,
there is no need for the user to do it.

Thank you very much,
for having it fixed in record time. 🔝 

Best regards,
have a nice weekend! 😃
