### ISSUE TITLE
ImportError: cannot import name make_password_dialog

### ISSUE THREAD

**Issue by camponez** [spesmilo/electrum#2286]
After upgrade to 2.8.0

  File "/usr/local/lib/python2.7/dist-packages/electrum_plugins/btchipwallet.py", line 10, in <module>
    from electrum_gui.qt.password_dialog import make_password_dialog, run_password_dialog
  ImportError: cannot import name make_password_dialog

Python 2.7
Ubuntu 16.04

**Comment by ecdsa** [comment]
this is a leftover file from an old install.
rm -rf /usr/local/lib/python2.7/dist-packages/electrum_plugins and install again.
